### PR TITLE
Fix links to mailing lists.

### PR DESCRIPTION
**Pull request by cwest**

### CODE REVIEW

**Comment by cwest** [comment]
@JacquesPerrault @chipchilders @Lcrowther-pivotal 

Pinging a few recent committers on this PR. :smile:

**Comment by chipchilders** [comment]
published as well. Thanks for the PR @cwest

**Comment by cwest** [comment]
I don't see if live, @chipchilders, but I appreciate the merge at least! http://cloudfoundry.org/get-in/index.html — Still the old content.

**Comment by chipchilders** [comment]
@cwest the cache strikes again ;-)

**Pull request merged**
